---
title: "201-additional-fish"
output: html_document
date: "2026-09-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(pcadapt)
library(viridis)
library(ggplotify)
library(pheatmap)
library(ggrepel)
library(ggpubr)
library(grid)
library(raster)
library(ozmaps)
library(snpR)
library(ggrepel)
library(ggspatial)
```

Including the extra data from Taiwan and Aquaculture

```{r}
m118<-read_csv("meta/mq-with-extras.csv")
m118
```
```{r}
unique(m118$Group)
```

```{r}
m118$Group<-factor(m118$Group, levels=c("Daly River","Roper River","Mainstream","Burdekin","FitzroyQLD","Fly River","Australian Aquaculture","Indonesia-K","Indonesia-SU",
                                        "Indonesia-SJ","Tamsui River","Sri Lanka"))


ggplot(m118) +
  geom_histogram(aes(x=Coverage, fill=Group)) +
  scale_fill_viridis_d(option="magma") +
  theme_bw() +
  ylab("Count\n") +
  xlab("\nCoverage") 
```



```{r}
m118 %>% dplyr::select(Path) %>% write_tsv("~/github/barra-lh/bamlists/118.bamlist", col_names = FALSE)
m118 %>% dplyr::select(specimen_id) %>% write_tsv("~/github/barra-lh/bamlists/118.names", col_names = FALSE)

gg<-read_csv("meta/mq-genos.csv")
m118<-m118 %>% left_join(gg)
meta<-m118

```
```{sh, eval=FALSE}
srun -t 2:00:00 -p bmh --mem=48G --nodes=1 --ntasks-per-node=1 --cpus-per-task=12 $HOME/angsd/angsd -nthreads 12 \
-minInd 112 -bam bamlists/118.bamlist -ref genome/GCF_001640805.2_TLL_Latcal_v3_genomic.fna \
-r NC_066847.1:13250000-13450000 -out outputs/201/lca15-01  \
-minMaf 0.10 -minMapQ 20 -minQ 20 -GL 1 -doGLF 2 -doMajorMinor 1 -doMaf 1 -SNP_pval 1e-6 \
-doGeno 2 -doPost 1 -postCutoff 0.95 -doVcf 1  > outputs/201/lca15-01.out 2> outputs/201/lca15-01.err &

bcftools reheader --samples bamlists/118.names -o outputs/201/lca15-renamed-10.vcf.gz outputs/201/lca15-01.vcf.gz

```


```{r}
vcf<-read.vcfR(file="outputs/201/lca15-renamed-10.vcf.gz")

genind<-vcfR2genind(vcf)
genind@pop<-as.factor(meta$NewPhenotype)

gen<-genind
X <- tab(gen, NA.method="mean")

pca1 <- dudi.pca(X,scannf=FALSE,scale=FALSE,nf=3)

df<-pca1$li
df<-df %>% bind_cols(meta)
eig<-pca1$eig/sum(pca1$eig)*100


pc12<-ggplot(df) + 
  geom_point(aes(x=Axis1, y=Axis2, fill=Lineage), pch=21, alpha=0.75, cex=2) +
  theme_bw() +
  xlab(paste0("PC1 ",round(eig[1],2), "%")) +
  ylab(paste0("PC2 ",round(eig[2],2), "%")) +
  theme(panel.grid = element_blank()) +
  guides(fill = guide_legend(override.aes = list(pch = 22))) +
  theme(legend.position = "top") 
pc12
```
